server:
  port: 9334


apollo:
  bootstrap:
    enabled: true
  namespaces: application


management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /

pebble:
  prefix: /templates/
  suffix: .html
  content-type: text/html


spring:
  application:
    name: spot-market-maker
  profiles:
    active: prod



  #数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    initialSize: 1000
    minIdle: 5
    maxActive: 1000
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
    url: jdbc:mysql://127.0.0.1:3306/contract_quant?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 5W0f9BnwPHtlrxQENL3jzI4O


mybatis:
  mapper-locations: classpath*:mybatis/*.xml

yoyo-spot:
  host: https://api.bitwired.com
  apiid: uo3a6u07df2R8Z4TICDaKAWv5Rfo24dL
  privateKey: Kr8tsJcLjV2tOM13JMouaKRGNf7uCGnz
